# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2018-01-10 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0002_auto_20180110_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='GUID'),
        ),
        migrations.AddField(
            model_name='grade',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='GUID'),
        ),
        migrations.AddField(
            model_name='poi',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='GUID'),
        ),
        migrations.AddField(
            model_name='trailsection',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='GUID'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='name',
            field=models.CharField(help_text='Enter name of the Point of Interest.', max_length=255, verbose_name='Name of Point of Interest(POI)'),
        ),
    ]
